site_name: Satyrn
repo_url: https://github.com/CharlesAverill/satyrn
site_description: Satyrn is an alternative to Jupyter notebooks that supports branching code cells and network collaboration.
site_author: Charles Averill
nav:
  - Quick Start: "index.md"
  - Introduction: "introduction.md"
  - CLI: "cli.md"
  - Contributing: "CONTRIBUTING.md"
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
